# .github/workflows/build-and-publish.yml
name: Build and Publish Lambda Artifact

# Aciona o pipeline quando um push é feito na branch 'main'
on:
  push:
    branches:
      - main

jobs:
  
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Necessário para autenticação segura com a AWS (OIDC)
      contents: read  # Necessário para fazer o checkout do código

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate version number
        id: get_version
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml -Drevision=${{ steps.get_version.outputs.VERSION }} -DskipTests
          # Rename the final fat jar to .zip for clarity and direct upload
          mv target/cpf-auth-lambda-${{ steps.get_version.outputs.VERSION }}.jar target/cpf-auth-lambda-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }} # ex: us-east-1

      - name: Upload artifact to S3
        run: |
          aws s3 cp \
            target/cpf-auth-lambda-${{ steps.get_version.outputs.VERSION }}.zip \
            s3://${{ secrets.ARTIFACT_BUCKET }}/cpf-auth-lambda/${{ steps.get_version.outputs.VERSION }}/cpf-auth-lambda-${{ steps.get_version.outputs.VERSION }}.zip
